name: cd
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - "newpolicy2"
  workflow_dispatch:

jobs:
  cd:
    env: **
      TF_IN_AUTOMATION: true
      TF_INPUT: false
      TF_CLI_ARGS_apply: "-auto-approve -parallelism=30"
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ~1.4.2

      - name: Terraform Init
        id: init
        run: terraform init -no-color
        working-directory: newpolicy2

      - name: Terraform Apply
        id: apply
        if: ${{ success() }}
        run: terraform apply
        working-directory: newpolicy2

      - name: Azure Login
        uses: azure/login@v1
        if: ${{ failure() }} || ${{ success() }}
        with:
          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'
          enable-AzPSSession: true
